os: osx
osx_image: xcode12.2

addons:
  homebrew:
    update: true
    packages:
      - coreutils
      - ninja
      - libtool
      - automake
      - cmake
      - pkg-config
      - gettext

script:
  - download_gettext=true clean=true build_libnvim=true ./NvimServer/bin/build_nvimserver.sh
